/-
Copyright (c) 2026 Wayne Brassem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Wayne Brassem
-/

import Mathlib

/-!

# Division Words for Collatz Trajectories

This module develops the basic dynamical and symbolic definitions used to
encode fully accelerated Collatz trajectories by their `2`-adic division
counts.

The fully accelerated map is

`f(x) = (3 * x + 1) / 2^(v₂(3 * x + 1))`.

The development has the following basic structure:

        `division_count`
              │
              ▼
      `fully_accelerated`
              │
              ├──────────────► `fully_accelerated_odd`
              │
              ▼
      `division_counts`
              │
              ├──────────────► positivity of generated counts
              │
              ▼
        division words
              │
              ├──────────────► validity
              │
              ├──────────────► admissibility
              │
              ▼
         `realizes`
              │
              ▼
generated symbolic trajectory data

The first layer establishes the arithmetic needed for the fully accelerated
map. The exponent `division_count x` is defined by the `2`-adic valuation of
`3 * x + 1`, so the corresponding power of `2` divides the numerator
exactly. Removing that full power of `2` leaves an odd quotient. In
particular, `fully_accelerated x` is odd for every natural number `x`, and
when `x` is odd its division count is positive.

The second layer packages successive division counts into finite lists.
A `division_word` is an abstract finite sequence of natural numbers, while
`division_counts x m` is the concrete word generated by the first `m`
states of the accelerated trajectory beginning at `x`.

The module deliberately distinguishes several notions:

* a division word is an arbitrary finite symbolic sequence;
* a valid division word is nonempty;
* an admissible division word is valid and has every entry at least `1`;
* `realizes x ω` means that `ω` is exactly the division-count sequence
  generated from `x`.

Thus admissibility is a symbolic condition, while realizability is a
dynamical condition. No equivalence between the two is assumed here.

The module also establishes elementary structural facts needed later,
including:

* positivity of the division counts generated from odd starting values;
* admissibility of nonempty generated division-count words;
* preservation of word length by `division_counts`;
* the bound `ω.length ≤ total_division_count ω` for admissible words.

These definitions and lemmas provide the dynamical foundation for the
formal affine representation developed in `Collatz.Affine`.

-/

/- Open the Collatz namespace. -/
namespace Collatz

/-- The 2-adic division count for a natural number undergoing a Collatz iteration. -/
def division_count (x : ℕ) : ℕ :=
  padicValNat 2 (3 * x + 1)

/-- For a natural number n = 2^k m, with m odd means 2-adic(n) = k. -/
lemma valuation_exponent_of_odd_factor
  {n k m : ℕ}
  (hn : n = 2 ^ k * m)
  (hm : Odd m)
  (hn0 : n ≠ 0) :
  padicValNat 2 n = k := by
    /- Rewrite n with 2 ^ k * m in hdiv, so 2 ^ k | 2 ^ k * m. -/
    have hdiv : 2 ^ k ∣ n := by
      rw [hn]
      exact dvd_mul_right (2 ^ k) m
    /- Since 2 ^ k divides n, padicValNat_dvd_iff_le gives k ≤ padicValNat 2 n. -/
    have h_lower : k ≤ padicValNat 2 n := by
      /- Maps the hdiv equivalence relation from 2 ^ k | n to k ≤ padicValNat 2 n. -/
      exact (padicValNat_dvd_iff_le (p := 2) (a := n) (n := k) hn0).mp hdiv
    /- Proof by contradiction tactic. -/
    have h_upper : padicValNat 2 n ≤ k := by
      by_contra h
      /- Assume the opposite of h_upper. For natural numbers, ¬(v ≤ k) implies k + 1 ≤ v. -/
      have hval : k + 1 ≤ padicValNat 2 n := by
        omega
      /- Since k + 1 ≤ padicValNat 2 n, the valuation theorem gives 2^(k + 1) ∣ n. -/
      have hpow : (2 : ℕ) ^ (k + 1) ∣ n := by
        exact (padicValNat_dvd_iff_le
          (p := 2) (a := n) (n := k + 1) hn0).mpr hval
      /- Rewrite n using hn so that the divisibility statement exposes
      the assumed factorization n = 2^k * m. -/
      have hpow' : (2 : ℕ) ^ (k + 1) ∣ 2 ^ k * m := by
        rw [hn] at hpow
        exact hpow
      /- Rewrite 2^(k + 1) as 2^k * 2 using the power recursion theorem. -/
      rw [pow_succ] at hpow'
      /- The cancellation theorem sees 2^k as its common factor.
      It therefore requires a proof that 0 < 2^k; `positivity` supplies it. -/
      have htwo : (2 : ℕ) ∣ m := by
        exact Nat.dvd_of_mul_dvd_mul_left (by positivity) hpow'
      /- Since hm : Odd m means that m = 2 * k + 1 for some k,
      unpack hm to obtain that witness and equation. -/
      have hodd : ¬ (2 : ℕ) ∣ m := by
        /- Assume 2 divides m and unpack the divisibility proof:
          m = 2 * j for some j. -/
        rintro ⟨j, hj⟩
        /- Unpack hm : Odd m:
          m = 2 * k + 1 for some k. -/
        rcases hm with ⟨k, hk⟩
        /- Now m is simultaneously 2 * j and 2 * k + 1, which is impossible. -/
        omega
      /- Contracition 2 | m and ¬2 | m -/
      exact hodd htwo
    /- If each is less than or equal to the other, then they are equal. -/
    exact Nat.le_antisymm h_upper h_lower

/--
The factor remaining after removing the full 2-adic part is odd.

Since every nonzero natural number can be written as 2^k * m
with m odd, valuation_exponent_of_odd_factor identifies k with
the 2-adic valuation. Dividing by that power therefore leaves m.
-/
lemma odd_part_of_padicValNat
    {n : ℕ} (hn0 : n ≠ 0) :
    Odd (n / 2 ^ padicValNat 2 n) := by
  /- Extract k, m, Odd m, and n = 2^k * m from
     Nat.exists_eq_two_pow_mul_odd. -/
  obtain ⟨k, m, hm, hn⟩ :=
    Nat.exists_eq_two_pow_mul_odd hn0
  /- Use the previous lemma to establish that k is exactly
     the 2-adic valuation of n. -/
  have hval : padicValNat 2 n = k :=
    valuation_exponent_of_odd_factor hn hm hn0
  /- First replace the 2-adic valuation by k, then replace n
     by its decomposition 2^k * m. -/
  rw [hval, hn]
  /- Simplify (2^k * m) / 2^k to m. -/
  norm_num
  /- The resulting goal is exactly the oddness fact extracted
     above from Nat.exists_eq_two_pow_mul_odd. -/
  exact hm

/--
The fully accelerated Collatz map is defined on the natural numbers.
It is a well-defined function which maps natural numbers to natural numbers.
The map is defined as follows and leverages the division count definition.
-/
def fully_accelerated (x : ℕ) : ℕ :=
  (3 * x + 1) / 2 ^ (division_count x)

/-- The fully accelerated Collatz map always produces an odd natural number. -/
lemma fully_accelerated_odd (x : ℕ) :
    Odd (fully_accelerated x) := by
  /- Expand fully_accelerated. -/
  unfold fully_accelerated
  /- Expand division_count within this. -/
  unfold division_count
  /- Infer that n := 3 * x + 1. -/
  exact odd_part_of_padicValNat (by omega)

/-- An odd natural number has a positive division count. -/
lemma division_count_pos
    (x : ℕ) (hx : Odd x) :
    1 ≤ division_count x := by
  /- Expand division_count. -/
  unfold division_count
  /- Establish 3 * x + 1 is even when x is odd. -/
  have heven : Even (3 * x + 1) := by
    /- An odd number times an odd number is odd. -/
    have h3x : Odd (3 * x) := by
      norm_num [Nat.odd_mul, hx]
    /- The sum of two odd numbers is even. -/
    exact h3x.add_odd odd_one
  /- Evenness implies divisibility by 2. -/
  have hdiv : (2 : ℕ) ∣ 3 * x + 1 := by
    exact Even.two_dvd heven
  /- Use the valuation characterization with exponent 1:
    2^1 ∣ (3 * x + 1) implies 1 ≤ padicValNat 2 (3 *x + 1). -/
  have hval : 1 ≤ padicValNat 2 (3 * x + 1) := by
      exact (padicValNat_dvd_iff_le
        (p := 2) (a := 3 * x + 1) (n := 1) (by norm_num)).mp hdiv
  /- hval is exactly the unfolded goal. -/
  exact hval

/--
A division word is a finite list of natural numbers intended to encode
division counts along a fully accelerated Collatz trajectory.
-/
abbrev division_word := List ℕ

/-- The first `m` division counts generated by `x`. -/
def division_counts (x m : ℕ) : division_word :=
  (List.iterate fully_accelerated x m).map division_count

/-- Every division count generated from an odd starting value is positive. -/
lemma division_counts_pos
    (x m : ℕ)
    (hx : Odd x) :
    ∀ d ∈ division_counts x m, 1 ≤ d := by
  /- Induct on the length `m` of the generated division-count list.
    The goal is to show every entry `d` in that list satisfies `1 ≤ d`. -/
  induction m generalizing x with
  /- The m=i=0 case represents the empty division word. -/
  | zero =>
     /- Simplify to nothing since there is nothing to iterate over. -/
      simp [division_counts]
  /- Assume the result for length `m` and prove it for length `m + 1`.
     The induction hypothesis `ih` is generalized over the starting value `x`. -/
  | succ m ih =>
    /- Introduce an arbitrary division count `d` and the hypothesis
      that `d` occurs in the length-(m+1) generated word. -/
    intro d hd
    /- Unfold the successor trace enough to expose membership as either
       membership in the head or in the remaining tail. -/
    simp only [division_counts, List.iterate] at hd
    /- Membership in the successor trace has two cases:
      `d` is the head division count, or `d` occurs in the tail. -/
    rcases hd with hhead | htail
    /- Head case: `d` is the current division count, which is positive
      because the current state `x` is odd. -/
    · exact division_count_pos x hx
    /- For (m + 1) rename the internal at iterator
        variable to htail for later use. -/
    · rename_i htail
      /- Apply the induction hypothesis to the tail trajectory, whose
         new starting value is `fully_accelerated x`.  Its oddness is
         supplied by `fully_accelerated_odd x`. -/
      apply ih
          (fully_accelerated x)
          (fully_accelerated_odd x)
          d
      /- The induction hypothesis leaves the goal
         d ∈ division_counts (fully_accelerated x) m.
         Rewrite that goal into the unfolded form in which `htail`
        is already stated. -/
      change d ∈ List.map division_count
        (List.iterate fully_accelerated (fully_accelerated x) m)
      /- `htail` is now the same membership proposition as the goal,
         written using `List.Mem` rather than the `∈` notation. -/
      exact htail

/-- A valid division word is a non-empty division word. -/
def valid_division_word (ω : division_word) : Prop :=
  0 < ω.length

/-- An admissible division word is one where each 2-adic factor is ≥ 1. -/
def admissible_division_word (ω : division_word) : Prop :=
  valid_division_word ω ∧ ∀ d ∈ ω, 1 ≤ d

/--
Every nonempty finite division-count trace generated from an odd
starting value is an admissible division word.
-/
lemma division_counts_admissible
    (x m : ℕ)
    (hx : Odd x)
    (hm : 0 < m) :
    admissible_division_word (division_counts x m) := by
  /- Expand admissibility into its two requirements:
     nonempty length and positivity of every entry. -/
  unfold admissible_division_word
  /- Prove the two conjuncts separately. -/
  constructor
  /- The generated list has length `m`, so `hm : 0 < m`
     proves that it is nonempty. -/
  · simpa [valid_division_word, division_counts] using hm
  /- Every generated division count is positive because the
     starting value is odd. -/
  · exact division_counts_pos x m hx

/-- A natural number `x` realizes the division word `ω` when `ω` is exactly
    the finite sequence of division counts generated by the first `ω.length`
    iterates starting from `x`. -/
def realizes (x : ℕ) (ω : division_word) : Prop :=
  ω = division_counts x ω.length

/-- The total division count of a division word is the sum of its entries. -/
def total_division_count (ω : division_word) : ℕ :=
  ω.sum

/-- The generated division-count word has the requested length. -/
lemma division_counts_length (x m : ℕ) :
    (division_counts x m).length = m := by
  simp [division_counts]

/--
If every entry of a division word is positive, then its length
is at most its total sum.
-/
lemma division_word_length_le_sum_of_pos
    (ω : division_word)
    (hpos : ∀ d ∈ ω, 1 ≤ d) :
    ω.length ≤ ω.sum := by
  /- Move `hpos` back into the goal so that the induction
     hypothesis may assume positivity for the tail word. -/
  revert hpos
  /- Induct directly on the list representing the division word. -/
  induction ω with
  /- Empty word: both its length and its sum are zero. -/
  | nil =>
      intro hpos
      simp
  /- Assume the result for the tail `ω` and prove it for
     the word formed by prepending `d`. -/
  | cons d ω ih =>
      intro hpos
      /- The head entry is positive because it belongs to `d :: ω`. -/
      have hd : 1 ≤ d := by
        exact hpos d (by simp)
      /- Every entry of the tail is also an entry of `d :: ω`,
         so the positivity hypothesis restricts to the tail. -/
      have htail : ∀ e ∈ ω, 1 ≤ e := by
        intro e he
        exact hpos e (by simp [he])
      /- Apply the induction hypothesis to the tail. -/
      have ih' : ω.length ≤ ω.sum := by
        exact ih htail
      /- Adding the positive head preserves the inequality. -/
      calc
        (d :: ω).length = ω.length + 1 := by simp
        _ ≤ ω.sum + d := Nat.add_le_add ih' hd
        _ = d + ω.sum := by
          exact Nat.add_comm _ _
        _ = (d :: ω).sum := by simp

/--
The length of an admissible division word is at most
its total division count.
-/
lemma division_word_length_le_total
    {ω : division_word}
    (hω : admissible_division_word ω) :
    ω.length ≤ total_division_count ω := by
  /- Admissibility supplies nonemptiness and positivity.
     Only positivity is needed for this inequality. -/
  rcases hω with ⟨_, hpos⟩
  unfold total_division_count
  exact division_word_length_le_sum_of_pos ω hpos

/- End of the Collatz namespace. -/
end Collatz
